---

- name: Install Atom
  homebrew_cask: name=atom state=present
  notify: brew cask cleanup

- name: Ensure Atom packages are installed
  command: apm install {{ item }}
  args:
    creates: "{{ ansible_env.HOME }}/.atom/packages/{{ item }}"
  with_items: "{{ atom_packages }}"

- name: Copy Atom config into place.
  copy:
    src: config.cson
    dest: "{{ ansible_env.HOME }}/.atom/config.cson"
    mode: 0644

- name: Upgrade Atom packages
  command: apm upgrade --no-confirm
  register: apm_upgrade
  # changed_when: apm_upgrade.stdout | !search("Package Updates Available (0)")
  when: atom_upgrade_packages

- debug:
  var: apm_upgrade

# TODO: provision project config & definitions (project-manager).
